version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mirrcgrhrcifuvajyjsb.supabase.co
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Ahmed_0183488994
      DB_NAME: postgres
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    environment:
      - API_URL=http://localhost:3000